### ISSUE TITLE
Accelerate scanning/reading using `bufio`

### ISSUE THREAD

**Issue by wangkuiyi** [wangkuiyi/recordio#50]
According to https://gobyexample.com/reading-files

> The bufio package implements a buffered reader that may be useful both for its efficiency with many small reads and because of the additional reading methods it provides.

Currently, the RecordIO Python wrapper calls the Go core to read from a file in the following way:

https://github.com/wangkuiyi/recordio/blob/c979fcd5a96888614f8127c26beaee8c8a2cc68a/python/crecordio.go#L122-L136

It passes `f` from `os.Open` to RecordIO scanner directly: 

```go
s := recordio.NewScanner(f, idx.idx, start, len)
```

We should try to add `bufio`

```go
s := recordio.NewScanner(bufio.NewReader(f), idx.idx, start, len)
```

and benchmark if this improves the reading speed.

**Comment by yhjust1** [comment]
It seems that we can't do this.
_bufio.Reader_ don't have Seek funtion(whick used in chunk.go,line [115),](https://github.com/wangkuiyi/recordio/blob/c979fcd5a96888614f8127c26beaee8c8a2cc68a/chunk.go#L115) This result in error
`./crecordio.go:133:42: cannot use bufio.NewReader(f) (type *bufio.Reader) as type io.ReadSeeker in argument to recordio.NewScanner:`
	`*bufio.Reader does not implement io.ReadSeeker (missing Seek method)
`

**Comment by yhjust1** [comment]
I install recordio successfully in Windows system, but when I use it,it report a error.
```
Traceback (most recent call last):
  File "image_label.py", line 8, in <module>
    import recordio
  File "D:\Envir\Python37\lib\site-packages\recordio\__init__.py", line 1, in <module>
    from .recordio import *
  File "D:\Envir\Python37\lib\site-packages\recordio\recordio.py", line 9, in <module>
    lib = ctypes.cdll.LoadLibrary(path)
  File "D:\Envir\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\Envir\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。
```
I don't think this is recordio's problem, because it works well in Ubuntu 16.04
